openapi: 3.0.0
info:
  title: home-assistant-ws-relay
  version: 1.0.0

paths:
  /api/hassio/push:
    x-yc-apigateway-websocket-connect:
      operationId: ha-push-open
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: ${FUNCTION_ID}
        tag: "$latest"
        service_account_id: ${SERVICE_ACCOUNT_ID}
        context:
          route: origin
    x-yc-apigateway-websocket-message:
      operationId: ha-push-msg
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: ${FUNCTION_ID}
        tag: "$latest"
        service_account_id: ${SERVICE_ACCOUNT_ID}
        context:
          route: origin
    x-yc-apigateway-websocket-disconnect:
      operationId: ha-push-close
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: ${FUNCTION_ID}
        tag: "$latest"
        service_account_id: ${SERVICE_ACCOUNT_ID}
        context:
          route: origin

  /{path+}:
    x-yc-apigateway-websocket-connect:
      operationId: ha-sub-open
      parameters:
        - name: path
          in: path
          required: true
          schema:
            type: string
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: ${FUNCTION_ID}
        tag: "$latest"
        service_account_id: ${SERVICE_ACCOUNT_ID}
        context:
          route: channel
    x-yc-apigateway-websocket-message:
      operationId: ha-sub-msg
      parameters:
        - name: path
          in: path
          required: true
          schema:
            type: string
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: ${FUNCTION_ID}
        tag: "$latest"
        service_account_id: ${SERVICE_ACCOUNT_ID}
        context:
          route: channel
    x-yc-apigateway-websocket-disconnect:
      operationId: ha-sub-close
      parameters:
        - name: path
          in: path
          required: true
          schema:
            type: string
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: ${FUNCTION_ID}
        tag: "$latest"
        service_account_id: ${SERVICE_ACCOUNT_ID}
        context:
          route: channel
