bridge:
  url: "ws://localhost:8080/api/hassio/push"
  authToken: "changeme"
  reconnect:
    initialDelayMs: 1000
    maxDelayMs: 30000
    backoffMultiplier: 2
  pingIntervalMs: 15000

wakeup:
  listenPort: 3001
  # pathPrefix: "/somepath/aaa"  # optional, must match HA_ORIGIN_BASE path in cloud function

target:
  url: "ws://localhost:9090"

reorder:
  c2tDelayMs: 100
  c2tMaxDelayMs: 350
  seqOrder: "descending"

logging:
  level: "info"
